import time
import logging
from typing import List, Tuple, Optional

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("SpeculativeRuntime")

class Model:
    """Base class for models to be used in runtime."""
    def __init__(self, name: str):
        self.name = name

    def generate_tokens(self, input_ids: List[int], n: int) -> List[int]:
        """Simulate token generation."""
        # In a real implementation, this would call the model's forward pass
        import random
        return [random.randint(100, 1000) for _ in range(n)]

    def verify_tokens(self, input_ids: List[int], draft_tokens: List[int]) -> Tuple[List[int], int]:
        """
        Simulates verification of draft tokens.
        Returns:
            (verified_tokens, first_mismatch_index)
        """
        # In a real implementation, the VerifierModel would run a single forward pass
        # over the combined input_ids + draft_tokens and check if the predictions match.
        import random

        # Simulate a random mismatch index to test the loop
        mismatch_index = random.randint(0, len(draft_tokens))

        # Correct tokens would be generated by the VerifierModel
        # For simulation, we'll just say tokens before mismatch_index are accepted
        verified_tokens = draft_tokens[:mismatch_index]

        # The VerifierModel also provides the CORRECT token at the mismatch position
        if mismatch_index < len(draft_tokens):
            # Replace the mismatched token with a "correct" one
            correct_token = 9999 # Simulated correct token
            verified_tokens.append(correct_token)

        return verified_tokens, mismatch_index

class StandardRuntime:
    """Standard autoregressive runtime for baseline comparison."""
    def __init__(self, model: Model):
        self.model = model

    def generate(self, input_ids: List[int], max_len: int = 50) -> List[int]:
        start_time = time.time()
        current_ids = list(input_ids)

        while len(current_ids) < max_len + len(input_ids):
            token = self.model.generate_tokens(current_ids, 1)[0]
            current_ids.append(token)

        end_time = time.time()
        tps = (len(current_ids) - len(input_ids)) / (end_time - start_time)
        logger.info(f"StandardRuntime: {tps:.2f} tokens/sec")
        return current_ids

class SpeculativeRuntime:
    """Speculative runtime implementing the Verifier Loop."""
    def __init__(self, draft_model: Model, verifier_model: Model, n: int = 5):
        self.draft_model = draft_model
        self.verifier_model = verifier_model
        self.n = n
        self.total_accepted = 0
        self.total_drafted = 0

    def generate(self, input_ids: List[int], max_len: int = 50) -> List[int]:
        start_time = time.time()
        current_ids = list(input_ids)

        while len(current_ids) < max_len + len(input_ids):
            # 1. Request n tokens from the DraftModel
            draft_tokens = self.draft_model.generate_tokens(current_ids, self.n)
            self.total_drafted += len(draft_tokens)

            # 2. Pass these tokens to the VerifierModel for single-pass validation
            verified_tokens, mismatch_idx = self.verifier_model.verify_tokens(current_ids, draft_tokens)

            # 3. Accept tokens until the first mismatch
            # The verified_tokens includes the correct token at the mismatch position
            current_ids.extend(verified_tokens)

            # Tracking acceptance rate
            # Number of draft tokens actually accepted
            accepted_count = mismatch_idx
            self.total_accepted += accepted_count

            # If we accepted all n tokens, the loop continues.
            # If we hit a mismatch, the correct token is already added via verified_tokens.
            # We break if we reach max_len.
            if len(current_ids) >= max_len + len(input_ids):
                break

        end_time = time.time()
        tps = (len(current_ids) - len(input_ids)) / (end_time - start_time)
        acceptance_rate = self.total_accepted / self.total_drafted if self.total_drafted > 0 else 0

        logger.info(f"SpeculativeRuntime: {tps:.2f} tokens/sec, Acceptance Rate: {acceptance_rate:.2%}")
        return current_ids

if __name__ == "__main__":
    # Simulation setup
    draft_model = Model("DraftModel-Small")
    verifier_model = Model("VerifierModel-32B")

    input_sequence = [1, 2, 3, 4, 5]

    print("--- Running Standard Runtime ---")
    std_runtime = StandardRuntime(verifier_model)
    std_runtime.generate(input_sequence)

    print("\n--- Running Speculative Runtime ---")
    spec_runtime = SpeculativeRuntime(draft_model, verifier_model, n=5)
    spec_runtime.generate(input_sequence)
